[package]
name = "database-manager"
version.workspace = true
edition.workspace = true

[dependencies]
dbm-core.workspace = true
dbm-driver-sqlite.workspace = true
dbm-driver-postgres.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
eframe = { version = "0.36", default-features = false, features = ["default_fonts", "glow", "persistence", "wayland", "x11"] }
egui_extras = "0.36"
egui-phosphor = "0.14"
rfd = "0.17"
keyring = "4"
toml = "1"
dirs = "7"
